export const CHANGE_SIZE = "CHANGE_SIZE";
export const SET_DELAY_REF = "SET_DELAY_REF";
export const CHANGE_DIMENSIONS = "CHANGE_DIMENSIONS";
export const SET_VISUALIZATION_ONGOING = "SET_VISUALIZATION_ONGOING";
